#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: 250a666
#
Name     : R-evaluate
Version  : 0.23
Release  : 118
URL      : https://cran.r-project.org/src/contrib/evaluate_0.23.tar.gz
Source0  : https://cran.r-project.org/src/contrib/evaluate_0.23.tar.gz
Summary  : Parsing and Evaluation Tools that Provide More Details than the
Group    : Development/Tools
License  : GPL-2.0 MIT
BuildRequires : buildreq-R

%description
command line behaviour of R.

%prep
%setup -q -n evaluate
pushd ..
cp -a evaluate buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1698881713

%install
export SOURCE_DATE_EPOCH=1698881713
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/evaluate/DESCRIPTION
/usr/lib64/R/library/evaluate/INDEX
/usr/lib64/R/library/evaluate/LICENSE
/usr/lib64/R/library/evaluate/Meta/Rd.rds
/usr/lib64/R/library/evaluate/Meta/features.rds
/usr/lib64/R/library/evaluate/Meta/hsearch.rds
/usr/lib64/R/library/evaluate/Meta/links.rds
/usr/lib64/R/library/evaluate/Meta/nsInfo.rds
/usr/lib64/R/library/evaluate/Meta/package.rds
/usr/lib64/R/library/evaluate/NAMESPACE
/usr/lib64/R/library/evaluate/NEWS.md
/usr/lib64/R/library/evaluate/R/evaluate
/usr/lib64/R/library/evaluate/R/evaluate.rdb
/usr/lib64/R/library/evaluate/R/evaluate.rdx
/usr/lib64/R/library/evaluate/help/AnIndex
/usr/lib64/R/library/evaluate/help/aliases.rds
/usr/lib64/R/library/evaluate/help/evaluate.rdb
/usr/lib64/R/library/evaluate/help/evaluate.rdx
/usr/lib64/R/library/evaluate/help/paths.rds
/usr/lib64/R/library/evaluate/html/00Index.html
/usr/lib64/R/library/evaluate/html/R.css
/usr/lib64/R/library/evaluate/tests/test-all.R
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/eval.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/replay.md
/usr/lib64/R/library/evaluate/tests/testthat/comment.R
/usr/lib64/R/library/evaluate/tests/testthat/data.R
/usr/lib64/R/library/evaluate/tests/testthat/error-complex.R
/usr/lib64/R/library/evaluate/tests/testthat/error.R
/usr/lib64/R/library/evaluate/tests/testthat/example-1.R
/usr/lib64/R/library/evaluate/tests/testthat/ggplot-empty-1.R
/usr/lib64/R/library/evaluate/tests/testthat/ggplot-empty-2.R
/usr/lib64/R/library/evaluate/tests/testthat/ggplot-loop.R
/usr/lib64/R/library/evaluate/tests/testthat/ggplot.R
/usr/lib64/R/library/evaluate/tests/testthat/interleave-1.R
/usr/lib64/R/library/evaluate/tests/testthat/interleave-2.R
/usr/lib64/R/library/evaluate/tests/testthat/order.R
/usr/lib64/R/library/evaluate/tests/testthat/parse.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-additions.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-clip.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-last-comment.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-loop.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-multi-layout.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-multi-layout2.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-multi-missing.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-multi.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-new.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-par.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-par2.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-persp.R
/usr/lib64/R/library/evaluate/tests/testthat/plot-strwidth.R
/usr/lib64/R/library/evaluate/tests/testthat/plot.R
/usr/lib64/R/library/evaluate/tests/testthat/raw-output.R
/usr/lib64/R/library/evaluate/tests/testthat/test-errors.R
/usr/lib64/R/library/evaluate/tests/testthat/test-eval.R
/usr/lib64/R/library/evaluate/tests/testthat/test-evaluate.R
/usr/lib64/R/library/evaluate/tests/testthat/test-graphics.R
/usr/lib64/R/library/evaluate/tests/testthat/test-output-handler.R
/usr/lib64/R/library/evaluate/tests/testthat/test-output.R
/usr/lib64/R/library/evaluate/tests/testthat/test-parse.R
/usr/lib64/R/library/evaluate/tests/testthat/test-replay.R
/usr/lib64/R/library/evaluate/tests/testthat/try.R
