#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-evaluate
Version  : 1.0.3
Release  : 124
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/evaluate_1.0.3.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/evaluate_1.0.3.tar.gz
Summary  : Parsing and Evaluation Tools that Provide More Details than the
Group    : Development/Tools
License  : GPL-2.0 MIT
BuildRequires : buildreq-R

%description
the command line behaviour of R.

%prep
%setup -q -n evaluate
pushd ..
cp -a evaluate buildavx2
popd
pushd ..
cp -a evaluate buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736802002

%install
export SOURCE_DATE_EPOCH=1736802002
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/evaluate/DESCRIPTION
/usr/lib64/R/library/evaluate/INDEX
/usr/lib64/R/library/evaluate/LICENSE
/usr/lib64/R/library/evaluate/Meta/Rd.rds
/usr/lib64/R/library/evaluate/Meta/features.rds
/usr/lib64/R/library/evaluate/Meta/hsearch.rds
/usr/lib64/R/library/evaluate/Meta/links.rds
/usr/lib64/R/library/evaluate/Meta/nsInfo.rds
/usr/lib64/R/library/evaluate/Meta/package.rds
/usr/lib64/R/library/evaluate/NAMESPACE
/usr/lib64/R/library/evaluate/NEWS.md
/usr/lib64/R/library/evaluate/R/evaluate
/usr/lib64/R/library/evaluate/R/evaluate.rdb
/usr/lib64/R/library/evaluate/R/evaluate.rdx
/usr/lib64/R/library/evaluate/help/AnIndex
/usr/lib64/R/library/evaluate/help/aliases.rds
/usr/lib64/R/library/evaluate/help/evaluate.rdb
/usr/lib64/R/library/evaluate/help/evaluate.rdx
/usr/lib64/R/library/evaluate/help/paths.rds
/usr/lib64/R/library/evaluate/html/00Index.html
/usr/lib64/R/library/evaluate/html/R.css
/usr/lib64/R/library/evaluate/tests/test-all.R
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/abort-error.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/rmd-abort-error.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/rmd-abort-error.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/rmd-stop-error-auto-entrace.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/rmd-stop-error-entrace-sewed.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/rmd-stop-error.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/stop-error-no-trace.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/stop-error-trace-calling-handler.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/stop-error-trace-trim.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/conditions/stop-error-trace-wch.txt
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/evaluate.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/evaluation.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/graphics.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/output-handler.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/output.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/replay.md
/usr/lib64/R/library/evaluate/tests/testthat/_snaps/watchout.md
/usr/lib64/R/library/evaluate/tests/testthat/helper.R
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-abort-error.R
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-abort-error.Rmd
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-stop-error-auto-entrace.Rmd
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-stop-error-no-trace.R
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-stop-error-sewed.Rmd
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-stop-error-trace-trim.R
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-stop-error-trace.R
/usr/lib64/R/library/evaluate/tests/testthat/ressources/with-stop-error-wch.R
/usr/lib64/R/library/evaluate/tests/testthat/test-conditions.R
/usr/lib64/R/library/evaluate/tests/testthat/test-evaluate.R
/usr/lib64/R/library/evaluate/tests/testthat/test-evaluation.R
/usr/lib64/R/library/evaluate/tests/testthat/test-flush-console.R
/usr/lib64/R/library/evaluate/tests/testthat/test-graphics.R
/usr/lib64/R/library/evaluate/tests/testthat/test-inject-funs.R
/usr/lib64/R/library/evaluate/tests/testthat/test-output-handler.R
/usr/lib64/R/library/evaluate/tests/testthat/test-output.R
/usr/lib64/R/library/evaluate/tests/testthat/test-parse_all.R
/usr/lib64/R/library/evaluate/tests/testthat/test-replay.R
/usr/lib64/R/library/evaluate/tests/testthat/test-reproducible-output.R
/usr/lib64/R/library/evaluate/tests/testthat/test-watchout.R
