#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-evaluate
Version  : 0.9
Release  : 29
URL      : http://cran.r-project.org/src/contrib/evaluate_0.9.tar.gz
Source0  : http://cran.r-project.org/src/contrib/evaluate_0.9.tar.gz
Summary  : Parsing and Evaluation Tools that Provide More Details than the
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: R-stringr
BuildRequires : R-stringr
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n evaluate

%build

%install
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library evaluate
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library evaluate


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/evaluate/DESCRIPTION
/usr/lib64/R/library/evaluate/INDEX
/usr/lib64/R/library/evaluate/LICENSE
/usr/lib64/R/library/evaluate/Meta/Rd.rds
/usr/lib64/R/library/evaluate/Meta/hsearch.rds
/usr/lib64/R/library/evaluate/Meta/links.rds
/usr/lib64/R/library/evaluate/Meta/nsInfo.rds
/usr/lib64/R/library/evaluate/Meta/package.rds
/usr/lib64/R/library/evaluate/NAMESPACE
/usr/lib64/R/library/evaluate/NEWS
/usr/lib64/R/library/evaluate/R/evaluate
/usr/lib64/R/library/evaluate/R/evaluate.rdb
/usr/lib64/R/library/evaluate/R/evaluate.rdx
/usr/lib64/R/library/evaluate/help/AnIndex
/usr/lib64/R/library/evaluate/help/aliases.rds
/usr/lib64/R/library/evaluate/help/evaluate.rdb
/usr/lib64/R/library/evaluate/help/evaluate.rdx
/usr/lib64/R/library/evaluate/help/paths.rds
/usr/lib64/R/library/evaluate/html/00Index.html
/usr/lib64/R/library/evaluate/html/R.css
